language: python
sudo: false
cache: pip

git:
  submodules: true

matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36

install:
  - pip install --ignore-installed --upgrade setuptools pip tox coveralls

script:
  - cd src
  - tox -vv

after_success: if [ "$TOXENV" == "py36" ]; then coveralls; fi

notifications:
  email: false
