name: Python Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      # Linux deps
      - name: Install Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update && sudo apt install gcc-arm-none-eabi
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade setuptools tox
      - name: Run Tests
        working-directory: src
        run: |
          tox -e py
      - name: Coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: src
        run: |
          python -m pip install --upgrade coveralls
          coveralls --service=github
        if: ${{ matrix.python == '3.8' }}

